# Generated by Django 2.0.1 on 2018-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180719_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='8128147.html', max_length=32),
        ),
    ]
