# Generated by Django 2.0.1 on 2018-07-19 18:21

import blog.utils.random_article_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180719_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default=blog.utils.random_article_id.article_id_num, max_length=32),
        ),
    ]
