# Generated by Django 2.0.1 on 2018-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180719_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(max_length=32),
        ),
    ]
